### ISSUE TITLE
Does not work on Unity 2020.3.14f1

### ISSUE THREAD

**Issue by christo** [valiafetisov/unity-webgl-multiplayer#12]
I tried following the instructions in the README and when i open the project in the latest version of Unity it says there are compile errors in the csharp scripts and recommended I open in "safe mode". I did this and see errors that advise replacing `GUIText` with `UI.Text` and `GUITexture` with `UI.Texture` which I attempted to do (including adding a `using` directive) but as this is my first exposure to Unity and C# I am not able to diagnose the build problems further.

Have you tried this in the latest version of Unity? Can you advise on how to update the code to work with this? Thanks in advance.

**Comment by valiafetisov** [comment]
Hey @christo, thanks for reporting this. Haven't opened this in Unity for a while. #13 should solve the issue. Can you please test and verify?

**Comment by valiafetisov** [comment]
I merged the fix that was tested by me. Feel free to reopen the issue if it still doesn't work for you on the main branch.

**Comment by christo** [comment]
Thanks @valiafetisov I'll try it soon

**Comment by karishma9712** [comment]
ggg
