### ISSUE TITLE
Getting rid of nodemon

### ISSUE THREAD

**Issue by ghost** [valiafetisov/unity-webgl-multiplayer#2]
I don't need it. In fact, it's causing more trouble than being helpful. 
So I want to get rid of it. But since the node script basically requires it to even boot, it may be needed to edit the package.json, but the second I do, I'll get swarmed by error messages
about script start being missing or app.js being an invalid command and stuff..

So, any idea how to make this bootable without nodemon?

**Comment by valiafetisov** [comment]
Hi @Inuyasha22, you can always start node.js programs with just `node app.js`. 

Nodemon is helpful if you going to develop server script farther – it will automatically restart the server after every script edit, otherwise you need to do this manually.
