### ISSUE TITLE
Nodejs Error: read ECONNRESET

### ISSUE THREAD

**Issue by AlexMeow** [valiafetisov/unity-webgl-multiplayer#5]
Hi, sorry for bothering you, I have some problems while trying your code.
While I'm running npm, I opened several web pages that connect to nodejs server, but when one web page closed or disconnected, the whole server will crush, and return this: **Error: read ECONNRESET**

I googled for these and someone said this is because there isn't an error handler, but I have tried to add an error handler, and nothing worked.

I'm wondering if I did anything wrong...
Thank you very much.

[This is a screenshot of this problem](https://i.imgur.com/VSZOMAf.png)

**Comment by valiafetisov** [comment]
> but when one web page closed or disconnected, the whole server will crush

Line 33 in `app.js` suppose to filter everyone who was disconnected:
https://github.com/valiafetisov/unity-webgl-multiplayer/blob/ab3a25cdf81b83ac26d8438d89854b1835689c7b/node/app.js#L32-L33

But if client was disconnected between line 33 and line 39 it will produce this error.

Thank you for catching this! I've added an error handler for that and also a general error handler in #6.
Would you be able to checkout this branch and test that it works now?

**Comment by AlexMeow** [comment]
Hi, thank you for responding me!
It still crushes with same error messages, I think there may be something wrong in my test steps?

Here are my steps:
1. Open a terminal, execute npm. 
1. Open the Unity project, build and run.
1. Wait for Unity finishes building and a web page which connects to my localhost will pop up.
1. Open several pages that connect to my localhost.
1. Check all the pages are connecting correctly, then randomly close one or more pages.

After step 5, the ECONNRESET error may occur, if not, I will randomly refresh some pages, and the error almost definitely happens after refreshing.

And here is my environment:
Unity version: 2019.4.3f1
Nodejs version: v12.18.4
npm version: 6.14.6

Thank you again!

**Comment by valiafetisov** [comment]
I was able to reproduce the error. I've updated the `ws` package and the error disappeared, see https://github.com/websockets/ws/issues/1256.

Please pull changes from #6 (or [download](https://github.com/valiafetisov/unity-webgl-multiplayer/archive/fix-econnreset.zip) fresh `fix-econnreset` branch) and `npm install && npm start` as usual.

Let me know if it solves the problem for you

**Comment by AlexMeow** [comment]
YES IT WORKS!!! (I never thought that `ws` package could cause this xD)
The problem has been totally solved, thank you so much!!!! :D
